[package]
name = "tlsh-sys"
version = "0.1.0"
edition = "2021"
links = "tlsh"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]

[build-dependencies]
cc = "1.0.83"
pkg-config = "0.3.27"

[features]
static = ["source"]
source = []
